### ISSUE TITLE
Getting behavior by name

### ISSUE THREAD

**Issue by arogachev** [nineinchnick/yii2-audit#9]
I think we should not rely on behavior name, and use class instead of that.

Users can omit the name or there is possibility of existence another behavior with the same name so they need to rename it.

Using class is more reliable, custom method for getting behavior by class can be used (just simple loop until first compliance), there is no built-in method for that.

**Comment by nineinchnick** [comment]
Yes, you're right.

**Comment by arogachev** [comment]
And if behavior attributes / methods names are pretty unique, we can directly call them like `$model->attributeName` and `$model->methodName()` without getting behavior.

**Comment by arogachev** [comment]
The latter is a bit ambiguous though, but I use this approach quite often.

**Comment by nineinchnick** [comment]
I prefer it fail with specific error message than just general 'method not found'. I'll make a getter for the behavior later on.
